version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nest_db
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: