// src/auth/auth.service.ts
import {
  ConflictException,
  Injectable,
  InternalServerErrorException,
  UnauthorizedException,
  Inject,
} from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import * as bcrypt from 'bcrypt';
import { eq } from 'drizzle-orm';
import { DRIZZLE } from '../db/db.provider';
import { users } from '../db/schema';
import type { MySql2Database } from 'drizzle-orm/mysql2';
import { SignupDto } from './dto/signup.dto';
import { LoginDto } from './dto/login.dto';

@Injectable()
export class AuthService {
  constructor(
    @Inject(DRIZZLE) private db: MySql2Database<typeof import('../db/schema')>,
    private jwtService: JwtService,
  ) {}

  async signup(dto: SignupDto) {
    // Check if user exists
    const existing = await this.db
      .select()
      .from(users)
      .where(eq(users.email, dto.email));
    if (existing.length > 0) {
      throw new ConflictException(
        'An account with this email address already exists',
      );
    }

    const hashedPassword = await bcrypt.hash(dto.password, 10);

    // Insert new user (UUID is auto-generated by default)
    await this.db.insert(users).values({
      name: dto.name,
      email: dto.email,
      password: hashedPassword,
      role: dto.role,
      picture: dto.picture || null,
    });

    // Fetch the newly created user to return it
    const [user] = await this.db
      .select()
      .from(users)
      .where(eq(users.email, dto.email));

    const token = this.generateToken(user.id, user.email, false);

    return {
      message: 'Account created successfully',
      access_token: token,
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role,
        picture: user.picture,
      },
    };
  }

  async login(dto: LoginDto) {
    const [user] = await this.db
      .select()
      .from(users)
      .where(eq(users.email, dto.email));

    if (!user) {
      throw new UnauthorizedException('Invalid email or password');
    }

    if (!user.password) {
      throw new UnauthorizedException(
        'This account was created using Google Sign-In. Please sign in with Google.',
      );
    }

    const isPasswordValid = await bcrypt.compare(dto.password, user.password);
    if (!isPasswordValid) {
      throw new UnauthorizedException('Invalid email or password');
    }

    const token = this.generateToken(user.id, user.email, dto.rememberMe);

    return {
      message: 'Signed in successfully',
      access_token: token,
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role,
        picture: user.picture,
      },
    };
  }

  async googleLogin(googleUser: {
    email: string;
    name: string;
    picture?: string;
  }) {
    if (!googleUser || !googleUser.email) {
      throw new UnauthorizedException(
        'Google authentication failed: Missing profile data',
      );
    }

    try {
      let [user] = await this.db
        .select()
        .from(users)
        .where(eq(users.email, googleUser.email));

      if (!user) {
        // Create new user
        await this.db.insert(users).values({
          email: googleUser.email,
          name: googleUser.name || 'Google User',
          picture: googleUser.picture || null,
          role: 'STUDENT',
        });
        // Fetch the newly created user
        [user] = await this.db
          .select()
          .from(users)
          .where(eq(users.email, googleUser.email));
      } else if (googleUser.picture && user.picture !== googleUser.picture) {
        // Update picture if changed
        await this.db
          .update(users)
          .set({ picture: googleUser.picture })
          .where(eq(users.id, user.id));
        // Refresh user data
        [user] = await this.db
          .select()
          .from(users)
          .where(eq(users.id, user.id));
      }

      const token = this.generateToken(user.id, user.email, true);

      return {
        message: 'Authenticated with Google successfully',
        access_token: token,
        user: {
          id: user.id,
          name: user.name,
          email: user.email,
          role: user.role,
          picture: user.picture,
        },
      };
    } catch (error) {
      console.error('Error during googleLogin database operation:', error);
      throw new InternalServerErrorException(
        'Database operational failure during Google login',
      );
    }
  }

  private generateToken(userId: string, email: string, rememberMe?: boolean) {
    const payload = { sub: userId, email };
    const expiresIn = rememberMe ? '30d' : '1d';
    return this.jwtService.sign(payload, { expiresIn });
  }
}
